OAuth2\ServerBundle\Entity\ClientPublicKey:
    type: mappedSuperclass
    id:
        client_id:
            type:       string
            length:     50
    fields:
        public_key:
            type:       text
    lifecycleCallbacks: {  }
